import {
  LayoutDashboard,
  Sprout,
  MapPin,
  CalendarRange,
  Wheat,
  ClipboardList,
  Boxes,
  Truck,
  Users,
  HandCoins,
  HardHat,
  Tractor,
  Receipt,
  FileBarChart,
  Settings,
  BookOpen,
  Bell,
  User as UserIcon,
  ChevronDown,
  ChevronUp,
  Check,
  CheckCircle2,
  Clock,
  ArrowUpRight,
  UserPlus,
  Moon,
  Sun,
  Menu,
  LogOut,
  Plus,
  Search,
  Phone,
  Pencil,
  Trash2,
  Home,
  Key,
  Wallet,
  Info,
  ShoppingCart,
  Building,
  Loader2,
  Activity,
  TrendingUp,
  Download,
  Printer,
  FileText
} from "lucide-react";

export const Icons = {
  // Navigation & Sidebar
  ShoppingCart: ShoppingCart,
  Dashboard: LayoutDashboard,
  Farms: Sprout,
  Lands: MapPin,
  Seasons: CalendarRange,
  Crops: Wheat,
  CropPrograms: BookOpen,
  Operations: ClipboardList,
  Inventory: Boxes,
  Suppliers: Truck,
  Customers: Users,
  Contractors: HardHat,
  Debts: HandCoins,
  Workers: Users, // The mockup shows "عمال" with a multiple users icon (similar to Users)
  Equipment: Tractor,
  Finance: Receipt,
  Reports: FileBarChart,
  Settings: Settings,
  Receipt: Receipt,

  // Topbar
  Bell: Bell,
  User: UserIcon,
  Moon: Moon,
  Sun: Sun,
  Menu: Menu,
  LogOut: LogOut,

  // Dashboard Stats & Lists
  Task: ClipboardList,
  ChevronDown: ChevronDown,
  ChevronUp: ChevronUp,
  Check: Check,
  CheckCircle: CheckCircle2,
  Clock: Clock,
  TrendingUp: ArrowUpRight,
  UserPlus: UserPlus,

  // Added missing direct aliases
  CalendarRange: CalendarRange,
  ArrowUpRight: ArrowUpRight,
  MapPin: MapPin,

  // Common UI Actions
  Plus: Plus,
  Search: Search,
  Phone: Phone,
  Edit: Pencil,
  Delete: Trash2,
  Home: Home,
  Key: Key,
  Users: Users,
  Sprout: Sprout,
  Wallet: Wallet,
  Info: Info,
  Close: Trash2,
  Building: Building,
  Spinner: Loader2,
  Activity,
  Download,
  Printer,
  FileText
};

export type IconType = typeof Icons[keyof typeof Icons];
